import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/theme.css";
import { CookieProvider } from "@/providers/cookie";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/context/ThemeContext";
import { FontProvider } from "@/context/FontProvider";
import { defaultColorConfig } from "@/config/default-colors.config";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { spaceGrotesk } from "@/fonts";
import CQueryClientProvider from "@/providers/queryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coditor",
  description: "Generated by create next app",
};

const getCookiesServer = async (value: string) => {
  const cookieStore = await cookies();
  const cookie = cookieStore.get(value);
  return cookie?.value;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getCookiesServer("theme");
  const font = await getCookiesServer("font");
  // console.log(" SERVER ---> ", theme, font);
  return (
    <html lang="en" data-theme={theme} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden h-screen`}
        style={{ background: "black" }}
      >
        <CQueryClientProvider>
          <ThemeProvider initialTheme={theme!}>
            <FontProvider initialFont={font!}>
              <CookieProvider>
                {children}
                <Toaster
                  position="top-right"
                  toastOptions={{
                    className: cn(
                      "px-4! py-2! text-[12px]! backdrop-blur-[4px] max-w-[400px]! w-fit! ",
                      spaceGrotesk.className
                    ),
                  }}
                />
              </CookieProvider>
            </FontProvider>
          </ThemeProvider>
        </CQueryClientProvider>
      </body>
    </html>
  );
}
