import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CookieProvider } from "@/providers/cookie";
import { themeConfig } from "@/config/themeConfig";
import { getCookies } from "@/helper/cookies";
import StyledAntdThemeProvider from "@/providers/StyledAntdThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCookie = getCookies("theme") || "app-dark";
  console.log("themeCookie ", themeCookie);
  const theme = themeConfig(themeCookie);

  console.log("[] => HHHH", theme);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-4 overflow-hidden h-screen`}
        style={{ background: "black" }}
      >
        <CookieProvider>
          <StyledAntdThemeProvider>
            {children}
          </StyledAntdThemeProvider>
        </CookieProvider>
      </body>
    </html>
  );
}
