import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/theme.css";
import { CookieProvider } from "@/providers/cookie";
import { themeConfig } from "@/config/themeConfig";
import { getCookies } from "@/helper/cookies";
import StyledAntdThemeProvider from "@/providers/StyledAntdThemeProvider";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCookiesServer = async (value: string) => {
  const cookieStore = await cookies();
  const cookie = cookieStore.get(value);
  return cookie?.value;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getCookiesServer("theme");
  // const font = await getCookiesServer("font");
  // console.log(theme,font)
  return (
    <html lang="en" data-theme={theme} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-4 overflow-hidden h-screen`}
        style={{ background: "black" }}
      >
        <CookieProvider>
          <StyledAntdThemeProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </StyledAntdThemeProvider>
        </CookieProvider>
      </body>
    </html>
  );
}
