export const QUERY_KEYS = {
    INDIVIDUAL: 'individual',
    BUSINESS: 'business',
    POST: 'post',
    LIKE: 'like',
    COMMENT: 'comment',
    INDUSTRY: 'industry',
    VERIFICATION_REQUEST: 'verification-request',
    DOCUMENT: 'document',
    FOLDER: 'folder',
    EMPLOYEE: 'employee',
    REVIEW: 'review',
    CHANNEL: 'channel',
    POLL_VOTE: 'poll-vote',

    PROFILE: 'Profile',
    ME: "me",

    CONNECTION: 'connection',
    CV: 'cv',
    CV_TEMPLATE: 'cv-template',
    NOTIFICATION: 'notification',
    CHAT: 'chat',
    MESSAGE: {
        BASE: 'message',
        LIST: 'message-list',
        RECENT_DOCUMENTS: 'message-recent-documents',
        DRAFTS: 'message-drafts',
        FORWARDED: 'message-forwarded',
    },
    WORKSPACE_CLIENT: 'workspace-client',
    WORKSPACE_PROJECT: 'workspace-project',
    WORKSPACE_PROJECT_MILESTONE: 'workspace-project-milestone',
    WORKSPACE_PROJECT_UPDATES: 'workspace-project-updates',
    WORKSPACE_PROJECT_TASK: 'workspace-project-task',
    WORKSPACE_DEPARTMENT: 'workspace-department',
    WORKSPACE_TEAMS: 'workspace-teams',
    WORKSPACE_NOTE: 'workspace-note',
    WORKSPACE_ASSOCIATION: 'workspace-association',
    WORKSPACE_DASHBOARD: 'workspace-dashboard',
    COMPLAINT: 'complaint',
};
